Fix predict import error in Streamlit UI
Fixed ImportError on Streamlit Cloud:
- Changed import from 'predict' to 'predict_game'
- Function was renamed from predict() to predict_game()
- Updated all calls to use new function signature

Old: from src.predict_api import predict
New: from src.predict_api import predict_game

Old: predict(game_id=...)
New: predict_game(game_input=...)

This fixes the blocking error:
'ImportError: cannot import name predict from src.predict_api'

Status: Import test passed ✅